name: skility_x
description: "A Flutter app for skill exchange, connect, offer, and request skills using Firebase, Riverpod, and MVVM architecture. Includes push notifications, caching and complete local testing support"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # googlle maps
  google_maps_flutter: ^2.12.1

  # firebase setup
  firebase_core: ^3.13.0

  # firebase auth
  firebase_auth: ^5.5.3

  # customized toasts
  toastification: ^3.0.2


  # caches image
  cached_network_image: ^3.4.1

  # for icon changes
  flutter_launcher_icons: ^0.14.3

  # icons
  material_design_icons_flutter: ^7.0.7296
  font_awesome_flutter: ^10.8.0

  #local db
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # helps in getting hive path
  path_provider: ^2.1.5

  # json model annotation
  json_annotation: ^4.9.0

  # ios icons
  cupertino_icons: ^1.0.8

  # state management
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1

  # extra layer for the variables security
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # classs model generator
  json_serializable: ^6.7.1 # lowered the version for compatibility with hive generator


  # hive generator
  hive_generator: ^2.0.1

  # built scripts ( ast development stage only)
  build_runner: ^2.4.15

flutter_lints: ^5.0.0


# icon change

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/skility_x_icon/skility_x.png"
  min_sdk_android: 23



flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/skility_x_icon/skility_x.png

    # for home skills screen
    - assets/skill_icons/

    # filter skills
    - assets/academic_skills/
    - assets/artistic_skills/
    - assets/languages/
    - assets/tech_skills/

    # arrows
    - assets/arrows/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: InterLight
      fonts:
        - asset: assets/font/Inter_18pt-Light.ttf
    - family: InterRegular
      fonts:
        - asset: assets/font/Inter_18pt-Regular.ttf
    - family: InterMedium
      fonts:
        - asset: assets/font/Inter_28pt-Medium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
